package main

// number of steps
const LOG_WRITE_FREQ = 10000

const POPULATION_SIZE = 101
const PREDATOR_POPULATION_SIZE = 1
const SUBPOPULATION_SIZE = (POPULATION_SIZE - PREDATOR_POPULATION_SIZE) / 2

const SIMULATION_SPACE_SIZE = 400
const SIMULATION_STEPS = 1000000

const STATIC_REPULSION_RADIUS = 1
const STATIC_REPULSION_RADIUS_SQUARED = STATIC_REPULSION_RADIUS * STATIC_REPULSION_RADIUS
const VIEW_DISTANCE = STATIC_REPULSION_RADIUS * (SIMULATION_SPACE_SIZE / 2)
const VIEW_DISTANCE_SQUARED = VIEW_DISTANCE * VIEW_DISTANCE

const UPDATE_DAMPENING_VALUE = 1

const PREY_SPEED = 5
const PREDATOR_SPEED = 6

const MUTATION_MOVEMENT = 10
const MUTATION_PREDATOR_REPULSION = 0.05
