package main

import "math"

// in generations
const POSITION_LOG_INTERVAL = 1
const STATISTICS_LOG_INTERVAL = 10
const EVOLUTION_INTERVAL = 5000

const POPULATION_SIZE = 81
const PREDATOR_POPULATION_SIZE = 1
const SUBPOPULATION_SIZE = (POPULATION_SIZE - PREDATOR_POPULATION_SIZE) / 2

const SIMULATION_SPACE_SIZE = 800
const GENERATIONS = 1000
const WARM_UP_PERIOD = 1000

const PREY_SPEED = 2
const PREDATOR_SPEED = 2.5

const STATIC_REPULSION_RADIUS = PREY_SPEED
const STATIC_REPULSION_RADIUS_SQUARED = STATIC_REPULSION_RADIUS * STATIC_REPULSION_RADIUS

const PREY_VIEW_DISTANCE = STATIC_REPULSION_RADIUS * 200
const PREY_VIEW_DISTANCE_SQUARED = PREY_VIEW_DISTANCE * PREY_VIEW_DISTANCE

const PREDATOR_VIEW_DISTANCE = STATIC_REPULSION_RADIUS * (SIMULATION_SPACE_SIZE / 4)
const PREDATOR_VIEW_DISTANCE_SQUARED = PREDATOR_VIEW_DISTANCE * PREDATOR_VIEW_DISTANCE

const MUTATION_MOVEMENT = 2
const MUTATION_PREDATOR_REPULSION = 0.005

var BLIND_ANGLE = math.Cos(math.Pi * 0.3)
var MAX_TURN_ANGLE_PREY = math.Pi / 30
var MAX_TURN_ANGLE_PREDATOR = math.Pi / 2
